<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sraquotes"
 *
 * Auto generated by Extension Builder 2022-09-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Random Quotes',
    'description' => 'Get quotes from external quote database (from Stämpfli AG) using their api.',
    'category' => 'plugin',
    'author' => 'Marc Wampfler',
    'author_email' => 'mwreg@outlook.com',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
